#!/usr/bin/expect

set addr [lindex $argv 0]
set port [lindex $argv 1]
set user [lindex $argv 2]
set password [lindex $argv 3]
spawn python3 main.py $addr $port
expect "JogoDaVelha>"
send "login ${user} ${password}\n"
expect "(y/N)"
send "y\n"
expect "JogoDaVelha>"
send "send 3 1\n"
expect "JogoDaVelha>"
send "send 1 2\n"
expect "JogoDaVelha>"
send "send 2 3\n"
expect "JogoDaVelha>"
send "send 1 1\n"
expect "JogoDaVelha>"
send "exit\n"
expect eof
